import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars = {
    Analisi1: [{type: 'autogenerated', dirName: 'analisi-1'}],
    Analisi2: [{type: 'autogenerated', dirName: 'analisi-2'}],  
    Analisi3: [{type: 'autogenerated', dirName: 'analisi-3'}], 
    Fisica1: [{type: 'autogenerated', dirName: 'fisica-1'}], 
    Fisica2: [{type: 'autogenerated', dirName: 'fisica-2'}], 
    Fismat: [{type: 'autogenerated', dirName: 'fismat'}],
    FisicaTeorica: [{type: 'autogenerated', dirName: 'fisica-teorica'}],
    Lab3: [{type: 'autogenerated', dirName: 'lab3'}],
    StoriaFisica: [{type: 'autogenerated', dirName: 'corsi-a-scelta/storia-fisica'}],
    MetodiComputazionali: [{type: 'autogenerated', dirName: 'corsi-a-scelta/metodi-computazionali'}],
  };

export default sidebars;
