import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars = {
    Analisi1: [{type: 'autogenerated', dirName: 'analisi-1'}],
    Analisi2: [{type: 'autogenerated', dirName: 'analisi-2'}],  
    Fisica1: [{type: 'autogenerated', dirName: 'fisica-1'}], 
    Fisica2: [{type: 'autogenerated', dirName: 'fisica-2'}], 
    Fismat: [{type: 'autogenerated', dirName: 'fismat'}],
    FisicaTeorica: [{type: 'autogenerated', dirName: 'fisica-teorica'}],
    Lab3: [{type: 'autogenerated', dirName: 'lab3'}],
  };

export default sidebars;
