import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars = {
    Analisi1: [{type: 'autogenerated', dirName: 'analisi-1'}],
    Analisi2: [{type: 'autogenerated', dirName: 'analisi-2'}],  
    Fisica1: [{type: 'autogenerated', dirName: 'fisica-1'}], 
  };

export default sidebars;
